name: Reusable release workflow

on:
  workflow_call:

jobs:
  release:
    name: Create a release
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'bump version to')"
    steps:
      - name: Extract version
        id: extract_version
        uses: frabert/replace-string-action@v1.1
        with:
          pattern: '^bump version to ([^\n]+).*$'
          string: ${{ github.event.head_commit.message }}
          replace-with: '$1'
          flags: 's'
      - name: Extract prerelease
        id: extract_prerelease
        uses: frabert/replace-string-action@v1.1
        with:
          pattern: '^[\d.]+(\.dev[\d]+|a[\d]+|b[\d]+|rc[\d]+)?$'
          string: ${{ steps.extract_version.outputs.replaced }}
          replace-with: '$1'
      - name: Show extracted version
        run: echo "${{ steps.extract_version.outputs.replaced }}"
      - name: Show extracted prerelease
        run: echo "${{ steps.extract_prerelease.outputs.replaced }}"
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v${{ steps.extract_version.outputs.replaced }}'
          name: 'Release ${{ steps.extract_version.outputs.replaced }}'
          generate_release_notes: true
          draft: false
          prerelease: ${{ steps.extract_prerelease.outputs.replaced != '' }}
          token: ${{ secrets.GITHUB_TOKEN }}
